### ISSUE TITLE
Could you elaborate on how this extension is compared to shellcheck?

### ISSUE THREAD

**Issue by singularitti** [bmalehorn/vscode-shell-syntax#1]
In README, you say spellcheck "provides advanced lint warnings but requires more commitment", which means it is better of not? What are the commitments?

**Comment by bmalehorn** [comment]
Sure.

Shell Syntax highlights only syntax errors. These errors prevent the program from being run at all. So they're bugs you'll **definitely** want to fix. Examples: missing `"` closing a string, empty function body.

![image](https://user-images.githubusercontent.com/3344958/85177313-b39ff380-b230-11ea-876e-7c154f0495b5.png)


Shellcheck highlights syntax errors and semantic hints. These hints are bugs that you'll **probably** want to fix, but aren't definitely a bug. For example if you set a variable and never read it, that might be a bug, and shellcheck will warn:

![image](https://user-images.githubusercontent.com/3344958/85177242-90754400-b230-11ea-8b9c-a9d6fda5d2a8.png)

The above code is a perfectly valid bash program, but I probably mean `echo "$count"` at the end.

Shellcheck is better in the sense that it's more strict. It catches more bugs. But sometimes you have to edit 1 line of a 1000 line script, and the script will have all sorts of Shellcheck warnings. In that case the warnings are not so helpful since you have to ignore most of them, and Shell Syntax would be more useful.

Personally, I use Shellcheck everywhere I can, but if I'm editing someone else's code and it doesn't pass Shellcheck, I fall back on Shell Syntax. Does that make sense?

**Comment by singularitti** [comment]
Understood. Thanks!
